fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - {
                    name: "styles",
                    items: [
                        "Format",
                        "-",
                        "JustifyLeft",
                        "JustifyCenter",
                        "JustifyRight",
                        "JustifyBlock",
                        "-",
                        "Bold",
                        "Italic",
                        "Underline",
                        "Strike",
                        "Blockquote",
                        "-",
                        "TextColor",
                        "BGColor",
                        "-",
                        "Link",
                        "RemoveFormat",
                        "-",
                        "NumberedList",
                        "BulletedList",
                        "-",
                        "Outdent",
                        "Indent",
                        "-",
                        "Image",
                        "Table",

                    ],
                }
