parameters:
    attachments_path: "%kernel.project_dir%/data/attachments"
    stripe_webhook_secret: "%env(STRIPE_WEBHOOK_SECRET)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $attachmentsPath: "%attachments_path%"
            $aiEndpointUri: "%env(AI_ENDPOINT_URI)%"
            $aiEndpointApiKey: "%env(AI_ENDPOINT_API_KEY)%"
            $aiEndpointModel: "%env(AI_ENDPOINT_MODEL)%"
            $stripeSecretKey: "%env(STRIPE_SECRET_KEY)%"
            $unioneApiKey: "%env(UNIONE_API_KEY)%"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
